### ISSUE TITLE
Use camunda-preferred connection pool (HikariCP)

### ISSUE THREAD

**Issue by galenatjpl** [NASA-AMMOS/common-workflow-service#41]
Periodically, we see issues like this:

```
org.springframework.transaction.CannotCreateTransactionException: Could not open JDBC Connection for transaction; nested exception is java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=cws-db-g71bt.cbtgh8rlzfls.us-gov-west-1.rds.amazonaws.com)(port=3306)(type=master) : Socket fail to connect to host:cws-db-g71bt.cbtgh8rlzfls.us-gov-west-1.rds.amazonaws.com, port:3306. Cannot assign requested address (connect failed)
at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:289)
at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:377)
at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
at org.camunda.bpm.engine.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:44)
at org.camunda.bpm.engine.impl.interceptor.ProcessApplicationContextInterceptor.execute(ProcessApplicationContextInterceptor.java:70)
at org.camunda.bpm.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:33)
at org.camunda.bpm.engine.impl.RuntimeServiceImpl.setVariables(RuntimeServiceImpl.java:394)
at org.camunda.bpm.engine.impl.RuntimeServiceImpl.setVariables(RuntimeServiceImpl.java:384)
at org.camunda.bpm.engine.impl.RuntimeServiceImpl.setVariable(RuntimeServiceImpl.java:371)
at jpl.cws.engine.CwsExternalTaskThread.setStringVariable(CwsExternalTaskThread.java:453)
at jpl.cws.engine.CwsExternalTaskThread.setOutputVariable(CwsExternalTaskThread.java:461)
at jpl.cws.engine.CwsExternalTaskThread.executeTask(CwsExternalTaskThread.java:571)
at jpl.cws.engine.CwsExternalTaskThread.runTask(CwsExternalTaskThread.java:231)
at jpl.cws.engine.CwsExternalTaskThread.run(CwsExternalTaskThread.java:108)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=cws-db-g71bt.cbtgh8rlzfls.us-gov-west-1.rds.amazonaws.com)(port=3306)(type=master) : Socket fail to connect to host:cws-db-g71bt.cbtgh8rlzfls.us-gov-west-1.rds.amazonaws.com, port:3306. Cannot assign requested address (connect failed)
at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1392)
at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:635)
at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:150)
at org.mariadb.jdbc.Driver.connect(Driver.java:89)
at org.springframework.jdbc.datasource.SimpleDriverDataSource.getConnectionFromDriver(SimpleDriverDataSource.java:140)
at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnectionFromDriver(AbstractDriverBasedDataSource.java:196)
at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnection(AbstractDriverBasedDataSource.java:159)
at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:246)
... 16 more
Caused by: java.sql.SQLNonTransientConnectionException: Socket fail to connect to host:cws-db-g71bt.cbtgh8rlzfls.us-gov-west-1.rds.amazonaws.com, port:3306. Cannot assign requested address (connect failed)
at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:183)
at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createSocket(AbstractConnectProtocol.java:255)
at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createConnection(AbstractConnectProtocol.java:519)
at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1387)
... 23 more
Caused by: java.net.ConnectException: Cannot assign requested address (connect failed)
at java.net.PlainSocketImpl.socketConnect(Native Method)
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
at java.net.Socket.connect(Socket.java:589)
at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createSocket(AbstractConnectProtocol.java:250)
... 25 more

```
I’m thinking this is the the camunda engine trying to progress the workflow itself..  I think CWS core should be upgraded to their preferred connection pool implementation.
see:  https://camunda.com/best-practices/_book/#_tuning_the_database_connection_pool

Camunda actually recommends we use this connection pool: https://github.com/brettwooldridge/HikariCP

**Comment by galenatjpl** [comment]
Criticality: high
Rough time estimate:  3 days
